apiVersion: v2
name: erp-engine
description: Helm chart for Salsabilah Amin Group - Core Business ERP Engine
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.15.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
