apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: erp-engine-servicemonitor
  namespace: erp-engine
  labels:
    release: prometheus
    app.kubernetes.io/name: erp-engine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: erp-engine
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
